### ISSUE TITLE
The plugin "transform-decorators-legacy" didn't export a Plugin instance

### ISSUE THREAD

**Issue by Gorzas** [rwjblue/ember-decorators#110]
I've just installed the library `ember-computed-decorators` and I have the following error:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (appTestTrees)] failed with:
TypeError: The plugin "transform-decorators-legacy" didn't export a Plugin instance
    at PluginManager.validate (/home/joseda/git/neuro-frontend/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/home/joseda/git/neuro-frontend/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/home/joseda/git/neuro-frontend/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/home/joseda/git/neuro-frontend/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/home/joseda/git/neuro-frontend/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/home/joseda/git/neuro-frontend/node_modules/broccoli-babel-transpiler/index.js:107:21)
    at Babel.processString (/home/joseda/git/neuro-frontend/node_modules/broccoli-babel-transpiler/index.js:206:25)
    at Promise.then.result.output (/home/joseda/git/neuro-frontend/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/home/joseda/git/neuro-frontend/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/home/joseda/git/neuro-frontend/node_modules/rsvp/dist/rsvp.js:1077:33)
```
After a time debugging I'm not able to find what's happening :(. I'm using Ember@2.12, Ember-cli-babel@6.4.1 and babel-plugin-transform-decorators-legacy@1.3.4; and I've followed the instructions on the README. Have anyone any about what's going on?

**Comment by rwjblue** [comment]
In general, this should be working.  Can you share your `ember-cli-build.js`?

FWIW, on ember-cli@2.12 you may need to use `babel6` as the key in your `ember-cli-build.js` instead of `babel` (due to some oddities that are hardcoded inside of ember-cli).

**Comment by Gorzas** [comment]
Using `babel6` as a key for ember-cli@2.12 works. Thanks @rwjblue. I paste the working ember-cli-build. May it be a good ide to add this info to the README of the library?

```
babel6: {
    plugins: [
      'transform-decorators-legacy',
      'transform-class-properties',
    ],
 },
```

**Comment by rwjblue** [comment]
See https://github.com/rwjblue/ember-decorators/issues/111. I think we can just do the work automatically for folks, the various permutations are pretty annoying to have in the README (and I can only imagine how annoying they are for users 😝 ).

**Comment by rwjblue** [comment]
I'm going to close this now (since things seem to be sorted out).
